### ISSUE TITLE
Basic Auth and raw body

### ISSUE THREAD

**Issue by he-mcardin** [calinrada/php-apidoc#24]
Hi!  Great work.
Could it be possible to add a Basic Auth feature when testing in sand box?
Also, some api calls need a body (POST, PUT) For example, a login call could need a JSON body in order to work:
POST /login
Body :
{
"username" : "string",
"password" : "password"
}
Could it be possible to add a way to edit this in Sandbox ?

**Comment by calinrada** [comment]
Hi @he-mcardin . Yes, it is possible to add BasicAuth. And related to methods, now you can send the parameters. For json body, should be easy to implement. My time is very limited these days, but I will try to come with an update over the weekend. Or feel free to contribute with a PR if you have more time.

**Comment by calinrada** [comment]
I have implemented basic auth. I'll try to implement raw body soon.

**Comment by he-mcardin** [comment]
Yes, excellent work! Thanks!

For raw body, I suggest you add it the same way you add a parameter :

@ApiParams(name="Body", type="*body*",description="...", [sample="{ json
template here... }"]);

This parameter type would add a textarea field. It could be useful to have
select containing the content's type : application/json, plain/text,
text/html or application/xml

I attached a screenshot to show you another simple feature that could be
very useful.

Best regards

M Cardin

2015-02-03 12:17 GMT-05:00 Calin Rada <notifications@github.com>:

> I have implemented basic auth. I'll try to implement raw body soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calinrada/php-apidoc/issues/24#issuecomment-72692420>.
>



-- 
*Matthieu Cardin*

Développeur Sénior / *Équation Humaine*
T. 514.876.1702  / *equationhumaine.co <http://equationhumaine.co/>*
1751 rue Richardson, bureau 4.400, Montréal (Qc), H3K 1G6

Suivez-nous / Follow-us: LinkedIn
<https://www.linkedin.com/company/equation-humaine> + Facebook
<https://www.facebook.com/equationhumaine> + Twitter
<https://twitter.com/human__equation>
#48 en 2014 au Profit 500
<http://www.profitguide.com/microsite/profit500/2014>


*Pensez à l'environnement avant d'imprimer ce courriel. / *

*Please consider the environment before printing this e-mail.*

*Avis :** Ce message est confidentiel. Si vous n’êtes pas le destinataire,
veuillez informer l’expéditeur par courriel immédiatement et effacer ce
message et en détruire toute copie.*



*Notice:** This message is confidential. If you are not the addressee,
please inform the sender by return e-mail immediately and delete this
message and destroy all copies.*
