### ISSUE TITLE
Sample param not being pulled on page

### ISSUE THREAD

**Issue by cameron-fgx** [calinrada/php-apidoc#28]
The sample parameter does not get pulled/displayed on the output page 

````
@ApiParams(name="...", type="...", nullable=..., description="...", [sample=".."])
````

**Comment by calinrada** [comment]
This is an example of a correct structure for annotations. Can you please check again

```php
    /**
     * @ApiDescription(section="Hashtags", description="Retrieve a list of hashtags")
     * @ApiMethod(type="get")
     * @ApiRoute(name="/hashtags")
     * @ApiParams(name="p", type="integer", nullable=true, description="Page number")
     * @ApiReturnHeaders(sample="HTTP 200 OK")
     * @ApiReturn(type="object", sample="{
     *  'items': [{
     *      'id':'int',
     *      'hashtag_name':'int',
     *      'hashtag_created_at':'string',
     *      'hashtag_updated_at':'string'
     *  }],
     *  'before':'int',
     *  'first':'int',
     *  'next':'int',
     *  'last':'int',
     *  'current':'int',
     *  'total_pages':'int',
     *  'total_items':'int',
     * }")
     */
```

**Comment by cameron-fgx** [comment]
Hi, yes this works as expected.

However,

>  @ApiParams(name="...", type="...", nullable=..., description="...", [sample=".."])

is referenced in the readme, under the "Available Methods" section
Perhaps it's just an oversight?

**Comment by calinrada** [comment]
[sample=".."] means that sample param is optional.

**Comment by cameron-fgx** [comment]
Yes.

But as the title of the issue suggests, where does the optional "sample" parameter get placed on the output page when it is included?

**Comment by calinrada** [comment]
See http://calinrada.github.io/php-apidoc/

**Comment by cameron-fgx** [comment]
![imgo](https://cloud.githubusercontent.com/assets/11272919/7613153/4c20a696-f98f-11e4-87e0-02ced9cc07b7.jpg)

**Comment by calinrada** [comment]
@cameron-fgx , sample is for the entire object. And goes to "Sample output tab". Currently there is no sample for an element/key

**Comment by cameron-fgx** [comment]
@calinrada This would make a nice feature, I'll implement and send a pull request.

**Comment by calinrada** [comment]
Great. Thx !
