### ISSUE TITLE
No way to access {{ body }} pane

### ISSUE THREAD

**Issue by cameron-fgx** [calinrada/php-apidoc#29]
The {{ body }} tag within the Tab pane cannot be accessed.

````
<div class="panel panel-default">
    <div class="panel-heading"><strong>Body</strong></div>
    <div class="panel-body">
        {{ body }}
    </div>
</div>
````

**Comment by gnuget** [comment]
The {{ body }} is accesible, the problem is to the option wasn't  mentioned in the readme file. 

I just created a PR adding this it in the file.
