### ISSUE TITLE
quoting and escaping problems in field's value specification

### ISSUE THREAD

**Issue by plessmann** [calinrada/php-apidoc#34]
When i try to return an sample @ApiReturn, its not possible to use double quotes within the string (the value so to say) and just using single quotes outside to specify the value. Its also not possible to escape the double quotes.

E.g.:
@ApiReturn(type="object", sample='{
     *  "transaction_id":"int",
     *  "transaction_status":"string"
     * }')
=> results that the sample data will be lost in the generated html doc.

If I try to escape the value like this:

@ApiReturn(type="object", sample="{
     *  \"transaction_id\":\"int\",
     *  \"transaction_status\":\"string\"
     * }")
=> will fail with a parsing exception:
There was an error generating the documentation: 
Parse Error: missing comma separator near: ...le="{\"transaction_id\":\"<--

You should fix it or add this to the "Known issues".

**Comment by gnuget** [comment]
I just create a PR with the fix, please be aware to first is necessary merge the PR which fix #20  in order to make this one work.
