### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by lycifer3** [calinrada/php-apidoc#43]
Fatal error: Uncaught Error: Class 'Crada\Apidoc\Builder' not found in C:\OpenServer\domains\vskidke\apidoc.php:16
Stack trace:
#0 {main}

  thrown in C:\OpenServer\domains\vskidke\apidoc.php on line 16

apidoc.php

<?php

use Crada\Apidoc\Builder;
use Crada\Apidoc\Exception;

$classes = [
    'frontend\controllers\CityApi',
    'frontend\controllers\CommentApi',
    'frontend\controllers\DiscountApi'
];

$output_dir  = **DIR**.'/apidocs';
$output_file = 'api.html'; // defaults to index.html

try {
    $builder = new Builder($classes, $output_dir, 'Api Title', $output_file);
    $builder->generate();
} catch (Exception $e) {
    echo 'There was an error generating the documentation: ', $e->getMessage();
}

**Comment by gotardo** [comment]
Hi,
If you are using composer to autoload this class, you will need to include the autoloader at the begining of your script:

```
<?php

include "vendor/autoload.php";

use Crada\Apidoc\Builder;
use Crada\Apidoc\Exception;

$classes = [
'frontend\controllers\CityApi',
'frontend\controllers\CommentApi',
'frontend\controllers\DiscountApi'
];

$output_dir = DIR.'/apidocs';
$output_file = 'api.html'; // defaults to index.html

try {
$builder = new Builder($classes, $output_dir, 'Api Title', $output_file);
$builder->generate();
} catch (Exception $e) {
echo 'There was an error generating the documentation: ', $e->getMessage();
}
```

... may be this should be included in the README file?
