### ISSUE TITLE
Laravel integration?

### ISSUE THREAD

**Issue by mcblum** [calinrada/php-apidoc#45]
Is there any way to integrate this into Laravel?

**Comment by calinrada** [comment]
This is framework independent. You can just create a simple php file with the contents similar to what @gotardo wrote here https://github.com/calinrada/php-apidoc/issues/43 . Example:


`
<?php

include "vendor/autoload.php";

use Crada\Apidoc\Builder;
use Crada\Apidoc\Exception;

$classes = [
    'PATH_TO_YOUR_CONTROLLER\YOUR_CONTROLLER.php',
];

$output_dir = DIR.'/apidocs';
$output_file = 'api.html'; // defaults to index.html

try {
    $builder = new Builder($classes, $output_dir, 'Api Title', $output_file);
    $builder->generate();
} catch (Exception $e) {
    echo 'There was an error generating the documentation: ', $e->getMessage();
}
`

**Comment by ZiperRom1** [comment]
I make it work fine on `Lumen`, here is the `apidoc.php` at the project root

```php
<?php
// Require the composer autoloader
require_once 'vendor/autoload.php';

use Crada\Apidoc\Builder;
use Crada\Apidoc\Exception;

$classes = array(
    'App\Http\Controllers\App' // App is a controller with class name App of course
);

$output_dir  = __DIR__ . '/public';
$output_file = 'index.html';

try {
    $builder = new Builder($classes, $output_dir, 'Api doc', $output_file);
    $builder->generate();
} catch (Exception $e) {
    echo 'There was an error generating the documentation: ', $e->getMessage();
}
```
