### ISSUE TITLE
Undefined Index laravel ?

### ISSUE THREAD

**Issue by rizwandogar111** [calinrada/php-apidoc#46]
Undefined index: sample in D:\Work\Workspace\htdocs\teraception-application-dashboard-web\vendor\crada\php-apidoc\Crada\Apidoc\Builder.php on line 320
**PHP Notice:**  Undefined index: sample in D:\Work\Workspace\htdocs\teraception-application-dashboard-web\vendor\crada\php-apidoc\Crada\Apidoc\Builder.php on line
 320

**Comment by ZiperRom1** [comment]
I make it work fine on `Lumen`, here is the `apidoc.php` att the project root

```php
<?php
// Require the composer autoloader
require_once 'vendor/autoload.php';

use Crada\Apidoc\Builder;
use Crada\Apidoc\Exception;

$classes = array(
    'App\Http\Controllers\App' // App is a controller with class name App of course
);

$output_dir  = __DIR__ . '/public';
$output_file = 'index.html';

try {
    $builder = new Builder($classes, $output_dir, 'Api doc', $output_file);
    $builder->generate();
} catch (Exception $e) {
    echo 'There was an error generating the documentation: ', $e->getMessage();
}
```

**Comment by solofeed** [comment]
The same issue. On 1.3.7 version

**Comment by calinrada** [comment]
@solofeed Now you are required to enter a sample for params. Eg: 

```php
@ApiParams(name="email", type="string", nullable=false, description="User email", sample="john@doe.com")
```

**Comment by solofeed** [comment]
@calinrada So I should update all php doc block for avoiding error?(
